---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vault-role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-sa
    namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  vault.hcl: |
    storage "inmem" {
    }

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  selector:
    matchLabels:
      app: vault
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault-sa
      volumes:
        - name: config
          configMap:
            name: vault-config
      containers:
        - name: vault
          image: vault:1.1.3
          args: ["server", "-config=/etc/vault/vault.hcl"]
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - mountPath: /etc/vault
              name: config
          livenessProbe:
            tcpSocket:
              port: 8200
          readinessProbe:
            httpGet:
              port: 8200
              path: /v1/sys/health?uninitcode=200
          ports:
            - containerPort: 8200
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  type: ClusterIP
  ports:
    - port: 8200
      targetPort: http
  selector:
    app: vault
