---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-vault-config
data:
  vault-agent.hcl: |
    vault {
            address = "http://vault:8200"
    }

    exit_after_auth = true

    auto_auth {
      method  "kubernetes" {
        mount_path = "auth/kubernetes"
        config {
          role = "app-sa"
        }
      }

      sink "file" {
        config {
          path = "/home/consul-template/.vault-token"
        }
      }
    }
  consul-template.hcl: |
    vault {
      renew_token = false
      vault_agent_token_file = "/home/consul-template/.vault-token"
      retry {
        backoff = "1s"
      }
    }
    template {
      destination = "/etc/secrets/super-password"
      contents = <<EOF
    {{- with secret "secrets/kv/data/super-password" -}}
    {{ .Data.data.password }}
    {{- end -}}
    EOF
    }
    template {
      destination = "/etc/secrets/cert-bundle"
      contents = <<EOF
    {{- with secret "secrets/pki/issue/app-sa" "common_name=app-sa.internal" -}}
    {{ .Data.certificate }}
    {{ .Data.private_key }}
    {{- end -}}
      EOF
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload
spec:
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      labels:
        app: workload
      annotations:
        config-version: v11
    spec:
      serviceAccountName: app-sa
      volumes:
        - name: consul-template
          emptyDir:
            medium: Memory
        - name: secrets
          emptyDir:
            medium: Memory
        - name: config
          configMap:
            name: workload-vault-config
      initContainers:
        - name: vault-agent
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          image: vault:1.1.3
          args: ["agent", "-config=/etc/vault-conf/vault-agent.hcl", "-log-level=debug"]
          volumeMounts:
            - mountPath: /home/consul-template
              name: consul-template
              readOnly: false
            - mountPath: /etc/vault-conf
              name: config
        - name: consul-template
          image: hashicorp/consul-template:alpine
          args: ["-config=/etc/consul-template-conf/consul-template.hcl", "-log-level=debug", "-once"]
          env:
            - name: VAULT_ADDR
              value: http://vault:8200
          volumeMounts:
            - mountPath: /home/consul-template
              name: consul-template
              readOnly: true
            - mountPath: /etc/consul-template-conf
              name: config
            - mountPath: /etc/secrets
              name: secrets
              readOnly: false
      containers:
        - name: workload
          image: alpine:latest
          command: ["/bin/sleep", "3600"]
          volumeMounts:
            - mountPath: /etc/secrets
              name: secrets
              readOnly: true
