---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-vault-config
data:
  vault-agent.hcl: |
    vault {
       address = "http://vault:8200"
    }
    exit_after_auth = true

    listener "tcp" {
       address = "127.0.0.1:8200"
       tls_disable = true
    }

    cache {
      use_auto_auth_token = true
    }

    auto_auth {
      method  "kubernetes" {
        mount_path = "auth/kubernetes"
        config {
          role = "app-sa"
        }
      }
    }

    template {
      source = "/etc/vault-conf/super-password.ctemplate"
      destination = "/etc/secrets/super-password"
    }

    template {
      source = "/etc/vault-conf/cert-bundle.ctemplate"
      destination = "/etc/secrets/cert-bundle"
    }
  super-password.ctemplate: |
    {{- with secret "secrets/kv/data/super-password" -}}
    {{ .Data.data.password }}
    {{- end -}}
  cert-bundle.ctemplate: |
    {{- with secret "secrets/pki/issue/app-sa" "common_name=app-sa.internal" -}}
    {{ .Data.certificate }}
    {{ .Data.private_key }}
    {{- end -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload
spec:
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      labels:
        app: workload
      annotations:
        config-version: v11
    spec:
      serviceAccountName: app-sa
      volumes:
        - name: secrets
          emptyDir:
            medium: Memory
        - name: config
          configMap:
            name: workload-vault-config
      initContainers:
        - name: vault-agent
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          image: vault:1.4.2
          args: ["agent", "-config=/etc/vault-conf/vault-agent.hcl", "-log-level=debug"]
          volumeMounts:
            - mountPath: /etc/vault-conf
              name: config
            - mountPath: /etc/secrets
              name: secrets
              readOnly: false
      containers:
        - name: workload
          image: alpine:latest
          command: ["/bin/sleep", "3600"]
          volumeMounts:
            - mountPath: /etc/secrets
              name: secrets
              readOnly: true
